### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by treeowl** [RyanGlScott/lift-generics#10]
Once #9 is merged ~~and the changelog is updated~~, I suspect I'll be pretty much permanently done here, modulo documentation tweaks. I believe a minor release would make sense.

**Comment by treeowl** [comment]
Changelog update rolled into #9.

**Comment by RyanGlScott** [comment]
I've uploaded [`lift-generics-0.2.1`](https://hackage.haskell.org/package/lift-generics-0.2.1) to Hackage.

**Comment by treeowl** [comment]
Yay!
