### ISSUE TITLE
Is it possible to make some older versions easier?

### ISSUE THREAD

**Issue by treeowl** [RyanGlScott/lift-generics#4]
The challenge before base 4.8 was getting the package name, because it wasn't yet available in the `Generic` metadata. Is this package name the same as the one you'd get from `Data.Typeable.tyConPackage`? That's been around since base 4.5. If it's the right name, then the friendly functions would just need `Typeable` constraints in that version range.

**Comment by RyanGlScott** [comment]
Based on my limited testing of old GHC versions, the package names that `Generic` and `Typeable` provide coincide.
