### ISSUE TITLE
Typeable deriving can be insufficiently polymorphic

### ISSUE THREAD

**Issue by treeowl** [RyanGlScott/lift-generics#8]
For GHC 7.8 and later, we should use *polykinded* `Typeable` so we don't need a totally monomorphic type.

Question: can we improve things any for earlier versions? Something like this might work:

```haskell
{-# language OverlappingInstances #-}
class HasPackage (a :: k) where
  getPackage :: proxy a -> String
instance Typeable t => HasPackage t where ...
instance Typeable1 t => HasPackage (t a) where ...
instance Typeable2 t => HasPackage (t a b) where ...
```

**Comment by RyanGlScott** [comment]
I'm lost. What does `Typeable` being poly-kinded have to do with `lift-generics`?

**Comment by treeowl** [comment]
All will be revealed very, very soon.
